window.BRAND_BESTSELLER_MODELS = [
  {
    "id": "brand-best-001",
    "year": 1972,
    "country": "意大利",
    "brand": "阿尔法·罗密欧",
    "model": "Alfa Romeo Alfasud",
    "kind": "电动车",
    "titleZh": "阿尔法·罗密欧 Alfa Romeo Alfasud",
    "titleEn": "Alfa Romeo Alfa Romeo Alfasud",
    "descZh": "阿尔法·罗密欧 Alfa Romeo Alfasud 在全球累计销量 约 1,017,387 台。主要装配地：装配地信息待补充。",
    "descEn": "The Alfa Romeo Alfasud is a small family car manufactured and marketed from 1971 to 1989 by Alfa Romeo as a front-engine, four-door, five-passenger entry-level model over a single generation — with facelifts in 1977 and 1980.",
    "production": 1017387,
    "salesUnits": 1017387,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Alfasud_orange.jpg/330px-Alfasud_orange.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Alfa_Romeo_Alfasud"
  },
  {
    "id": "brand-best-002",
    "year": 2017,
    "country": "法国",
    "brand": "阿尔派",
    "model": "Alpine A110 (2017)",
    "kind": "电动车",
    "titleZh": "阿尔派 Alpine A110 (2017)",
    "titleEn": "Alpine Alpine A110 (2017)",
    "descZh": "阿尔派 Alpine A110 (2017) 在全球累计销量 约 18,985 台。主要装配地：France: Dieppe。",
    "descEn": "The Alpine A110 is a rear mid-engine, rear-wheel-drive sports car introduced by French car manufacturer Alpine at the 87th Geneva International Motor Show in March 2017..",
    "production": 18985,
    "salesUnits": 18985,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "France: Dieppe",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Alpine_A110_S_Automesse_Ludwigsburg_2022_1X7A5946.jpg/330px-Alpine_A110_S_Automesse_Ludwigsburg_2022_1X7A5946.jpg",
    "policyScore": 44,
    "policyTagsZh": [
      "新能源补贴与排放法规提升电动化需求",
      "欧盟单一市场扩大规模化销售"
    ],
    "source": "https://en.wikipedia.org/wiki/Alpine_A110_(2017)"
  },
  {
    "id": "brand-best-003",
    "year": 2020,
    "country": "英国",
    "brand": "阿斯顿·马丁",
    "model": "Aston Martin DBX",
    "kind": "SUV",
    "titleZh": "阿斯顿·马丁 Aston Martin DBX",
    "titleEn": "Aston Martin Aston Martin DBX",
    "descZh": "阿斯顿·马丁 Aston Martin DBX 在全球累计销量 约 10,675 台。主要装配地：United Kingdom: St Athan, South Wales (Aston Martin Lagonda Saint Athan)。",
    "descEn": "The Aston Martin DBX is a crossover SUV produced by British luxury car marque Aston Martin since 2020.",
    "production": 10675,
    "salesUnits": 10675,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "United Kingdom: St Athan, South Wales (Aston Martin Lagonda Saint Athan)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/2021_Aston_Martin_DBX_in_Midnight_Blue%2C_front_left.jpg/330px-2021_Aston_Martin_DBX_in_Midnight_Blue%2C_front_left.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Aston_Martin_DBX"
  },
  {
    "id": "brand-best-004",
    "year": 1994,
    "country": "德国",
    "brand": "奥迪",
    "model": "Audi A4",
    "kind": "豪华车",
    "titleZh": "奥迪 Audi A4",
    "titleEn": "Audi Audi A4",
    "descZh": "奥迪 Audi A4 在全球累计销量 约 7,500,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Audi A4 is a line of luxury compact executive cars produced from 1994 to 2025 by the German car manufacturer Audi, a subsidiary of the Volkswagen Group.",
    "production": 7500000,
    "salesUnits": 7500000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Audi_A4_B9_sedans_%28FL%29_1X7A2441.jpg/330px-Audi_A4_B9_sedans_%28FL%29_1X7A2441.jpg",
    "policyScore": 10,
    "policyTagsZh": [
      "欧盟单一市场扩大规模化销售"
    ],
    "source": "https://en.wikipedia.org/wiki/Audi_A4"
  },
  {
    "id": "brand-best-005",
    "year": 2017,
    "country": "中国",
    "brand": "宝骏",
    "model": "Baojun 510",
    "kind": "SUV",
    "titleZh": "宝骏 Baojun 510",
    "titleEn": "Baojun Baojun 510",
    "descZh": "宝骏 Baojun 510 在全球累计销量 约 972,042 台。主要装配地：China: Liuzhou, Guangxi。",
    "descEn": "The Baojun 510 is a subcompact crossover SUV produced by SAIC-GM-Wuling through the Baojun brand..",
    "production": 972042,
    "salesUnits": 972042,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "China: Liuzhou, Guangxi",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Baojun_510_front.jpg/330px-Baojun_510_front.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Baojun_510"
  },
  {
    "id": "brand-best-006",
    "year": 1975,
    "country": "德国",
    "brand": "宝马",
    "model": "BMW 3 Series",
    "kind": "电动车",
    "titleZh": "宝马 BMW 3 Series",
    "titleEn": "BMW BMW 3 Series",
    "descZh": "宝马 BMW 3 Series 在全球累计销量 约 14,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The BMW 3 series is a line of compact executive cars manufactured by the German automaker BMW since May 1975.",
    "production": 14000000,
    "salesUnits": 14000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/BMW_G20_%282022%29_IMG_7316_%282%29.jpg/330px-BMW_G20_%282022%29_IMG_7316_%282%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/BMW_3_Series"
  },
  {
    "id": "brand-best-007",
    "year": 1959,
    "country": "美国",
    "brand": "别克",
    "model": "Buick LeSabre",
    "kind": "电动车",
    "titleZh": "别克 Buick LeSabre",
    "titleEn": "Buick Buick LeSabre",
    "descZh": "别克 Buick LeSabre 在全球累计销量 约 6,000,000 台。主要装配地：(main plant)Flint, Michigan, USA (Buick City)(branch assembly)Arlington, Texas, USA (Arlington Assembly)Doraville, Georg…。",
    "descEn": "The Buick LeSabre is a full-size car made by the division Buick of General Motors from 1959 until 2005.",
    "production": 6000000,
    "salesUnits": 6000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "(main plant)Flint, Michigan, USA (Buick City)(branch assembly)Arlington, Texas, USA (Arlington Assembly)Doraville, Georg…",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/1975_Buick_LeSabre_Custom_Landau_Hardtop.jpg/330px-1975_Buick_LeSabre_Custom_Landau_Hardtop.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Buick_LeSabre"
  },
  {
    "id": "brand-best-009",
    "year": 2005,
    "country": "中国",
    "brand": "比亚迪",
    "model": "BYD F3",
    "kind": "混动车",
    "titleZh": "比亚迪 BYD F3",
    "titleEn": "BYD BYD F3",
    "descZh": "比亚迪 BYD F3 在全球累计销量 约 1,684,904 台。主要装配地：装配地信息待补充。",
    "descEn": "The BYD F3 is a compact car that was produced by the Chinese car manufacturer BYD between 2005 and 2021.",
    "production": 1684904,
    "salesUnits": 1684904,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/2009_BYD_F3_1.5L%2C_front_8.3.18.jpg/330px-2009_BYD_F3_1.5L%2C_front_8.3.18.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/BYD_F3"
  },
  {
    "id": "brand-best-010",
    "year": 1959,
    "country": "美国",
    "brand": "凯迪拉克",
    "model": "Cadillac De Ville",
    "kind": "电动车",
    "titleZh": "凯迪拉克 Cadillac De Ville",
    "titleEn": "Cadillac Cadillac De Ville",
    "descZh": "凯迪拉克 Cadillac De Ville 在全球累计销量 约 3,870,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Cadillac DeVille is a model name used by Cadillac over eight generations, originally to designate a trim level of the 1949 Cadillac Series 62 and later for a standalone model in the brand range.",
    "production": 3870000,
    "salesUnits": 3870000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/2004_Cadillac_Deville_DHS_--_NHTSA.jpg/330px-2004_Cadillac_Deville_DHS_--_NHTSA.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Cadillac_De_Ville"
  },
  {
    "id": "brand-best-011",
    "year": 1958,
    "country": "美国",
    "brand": "雪佛兰",
    "model": "Chevrolet Impala",
    "kind": "电动车",
    "titleZh": "雪佛兰 Chevrolet Impala",
    "titleEn": "Chevrolet Chevrolet Impala",
    "descZh": "雪佛兰 Chevrolet Impala 在全球累计销量 约 16,500,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Chevrolet Impala is a full-size car that was built by Chevrolet for model years 1958 to 1985, 1994 to 1996, and 2000 to 2020.",
    "production": 16500000,
    "salesUnits": 16500000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Chevrolet_Impala_%2814373209694%29.jpg/330px-Chevrolet_Impala_%2814373209694%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Chevrolet_Impala"
  },
  {
    "id": "brand-best-012",
    "year": 1961,
    "country": "美国",
    "brand": "克莱斯勒",
    "model": "Chrysler Newport",
    "kind": "现代汽车",
    "titleZh": "克莱斯勒 Chrysler Newport",
    "titleEn": "Chrysler Chrysler Newport",
    "descZh": "克莱斯勒 Chrysler Newport 在全球累计销量 约 1,920,000 台。主要装配地：Jefferson Avenue AssemblyDetroit, MichiganLos Angeles (Maywood) AssemblyLos Angeles, California。",
    "descEn": "The Newport was a name used by Chrysler for both a hardtop body designation and also for its lowest priced model between 1961 and 1981.",
    "production": 1920000,
    "salesUnits": 1920000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Jefferson Avenue AssemblyDetroit, MichiganLos Angeles (Maywood) AssemblyLos Angeles, California",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/1962_Chrysler_-_Flickr_-_dave_7_%281%29.jpg/330px-1962_Chrysler_-_Flickr_-_dave_7_%281%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Chrysler_Newport"
  },
  {
    "id": "brand-best-013",
    "year": 1948,
    "country": "法国",
    "brand": "雪铁龙",
    "model": "Citroën 2CV",
    "kind": "现代汽车",
    "titleZh": "雪铁龙 Citroën 2CV",
    "titleEn": "Citroën Citroën 2CV",
    "descZh": "雪铁龙 Citroën 2CV 在全球累计销量 约 3,872,583 台。主要装配地：装配地信息待补充。",
    "descEn": "The Citroën 2CV is an economy car produced by the French company Citroën from 1948 to 1990.",
    "production": 3872583,
    "salesUnits": 3872583,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Citroen_2CV_1X7A7979.jpg/330px-Citroen_2CV_1X7A7979.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Citroën_2CV"
  },
  {
    "id": "brand-best-014",
    "year": 2008,
    "country": "罗马尼亚",
    "brand": "达契亚",
    "model": "Dacia Sandero",
    "kind": "电动车",
    "titleZh": "达契亚 Dacia Sandero",
    "titleEn": "Dacia Dacia Sandero",
    "descZh": "达契亚 Dacia Sandero 在全球累计销量 约 2,700,000 台。主要装配地：{{ubl。",
    "descEn": "The Dacia Sandero is a subcompact car/supermini (B-segment) car produced and marketed jointly by the French manufacturer Renault and its Romanian subsidiary Dacia since 2007, currently at its third generation.",
    "production": 2700000,
    "salesUnits": 2700000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/2023_Dacia_Sandero_III_DSC_6012.jpg/330px-2023_Dacia_Sandero_III_DSC_6012.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Dacia_Sandero"
  },
  {
    "id": "brand-best-015",
    "year": 1970,
    "country": "意大利",
    "brand": "德托马索",
    "model": "De Tomaso Pantera",
    "kind": "电动车",
    "titleZh": "德托马索 De Tomaso Pantera",
    "titleEn": "De Tomaso De Tomaso Pantera",
    "descZh": "德托马索 De Tomaso Pantera 在全球累计销量 约 7,260 台。主要装配地：Italy: Modena。",
    "descEn": "The De Tomaso Pantera is a mid-engine sports car produced by Italian automobile manufacturer De Tomaso from 1971 to 1992.",
    "production": 7260,
    "salesUnits": 7260,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Italy: Modena",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/De_Tomaso_Pantera_GT5-S_%287160836758%29.jpg/330px-De_Tomaso_Pantera_GT5-S_%287160836758%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/De_Tomaso_Pantera"
  },
  {
    "id": "brand-best-016",
    "year": 1949,
    "country": "美国",
    "brand": "道奇",
    "model": "Dodge Coronet",
    "kind": "电动车",
    "titleZh": "道奇 Dodge Coronet",
    "titleEn": "Dodge Dodge Coronet",
    "descZh": "道奇 Dodge Coronet 在全球累计销量 约 2,060,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Dodge Coronet is an automobile that was marketed by Dodge in seven generations, and shared nameplates with the same bodyshell with varying levels of equipment installed.",
    "production": 2060000,
    "salesUnits": 2060000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/1967_Dodge_Coronet_RT_2-door_hardtop%2C_front_left%2C_06-08-2024.jpg/330px-1967_Dodge_Coronet_RT_2-door_hardtop%2C_front_left%2C_06-08-2024.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Dodge_Coronet"
  },
  {
    "id": "brand-best-017",
    "year": 1983,
    "country": "意大利",
    "brand": "菲亚特",
    "model": "Fiat Uno",
    "kind": "两厢车",
    "titleZh": "菲亚特 Fiat Uno",
    "titleEn": "Fiat Fiat Uno",
    "descZh": "菲亚特 Fiat Uno 在全球累计销量 约 8,800,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Fiat Uno is a supermini manufactured and marketed by Fiat.",
    "production": 8800000,
    "salesUnits": 8800000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/2011_Fiat_Uno_1.4_Attractive.jpg/330px-2011_Fiat_Uno_1.4_Attractive.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Fiat_Uno"
  },
  {
    "id": "brand-best-018",
    "year": 1948,
    "country": "美国",
    "brand": "福特",
    "model": "Ford F-Series",
    "kind": "皮卡/卡车",
    "titleZh": "福特 Ford F-Series",
    "titleEn": "Ford Ford F-Series",
    "descZh": "福特 Ford F-Series 在全球累计销量 约 40,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Ford F-Series is a series of light-duty trucks marketed and manufactured by the Ford Motor Company since model year 1948 as a range of full-size pickup trucks — positioned between Ford's Ranger and Super Duty pickup trucks.",
    "production": 40000000,
    "salesUnits": 40000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ford_F-150_Lariat_Luxury_2022.jpg/330px-Ford_F-150_Lariat_Luxury_2022.jpg",
    "policyScore": 14,
    "policyTagsZh": [
      "轻型卡车政策与税制影响车型结构"
    ],
    "source": "https://en.wikipedia.org/wiki/Ford_F-Series"
  },
  {
    "id": "brand-best-019",
    "year": 2012,
    "country": "中国",
    "brand": "哈弗",
    "model": "Haval H6",
    "kind": "SUV",
    "titleZh": "哈弗 Haval H6",
    "titleEn": "Haval Haval H6",
    "descZh": "哈弗 Haval H6 在全球累计销量 约 3,892,260 台。主要装配地：China: TianjinBulgaria: Bahovitsa (Litex Motors)Iran: Golpayegan (Diar)。",
    "descEn": "The Haval H6 is a compact crossover SUV produced by the Chinese manufacturer Great Wall Motor under the Haval marque since 2011.",
    "production": 3892260,
    "salesUnits": 3892260,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "China: TianjinBulgaria: Bahovitsa (Litex Motors)Iran: Golpayegan (Diar)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Haval_H6_III_IMG001_%28cropped%29.jpg/330px-Haval_H6_III_IMG001_%28cropped%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Haval_H6"
  },
  {
    "id": "brand-best-020",
    "year": 1958,
    "country": "多国",
    "brand": "Hindustan Motors",
    "model": "Hindustan Ambassador",
    "kind": "现代汽车",
    "titleZh": "Hindustan Motors Hindustan Ambassador",
    "titleEn": "Hindustan Motors Hindustan Ambassador",
    "descZh": "Hindustan Motors Hindustan Ambassador 在全球累计销量 约 4,000,000 台。主要装配地：Hooghly, West Bengal, IndiaTiruvallur, Tamil Nadu, India。",
    "descEn": "The Hindustan Ambassador is an automobile manufactured by Indian manufacturer Hindustan Motors from 1957 to 2014.",
    "production": 4000000,
    "salesUnits": 4000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Hooghly, West Bengal, IndiaTiruvallur, Tamil Nadu, India",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/The_Classic_Ambassador_on_an_early_sunrise.jpg/330px-The_Classic_Ambassador_on_an_early_sunrise.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Hindustan_Ambassador"
  },
  {
    "id": "brand-best-021",
    "year": 1972,
    "country": "日本",
    "brand": "本田",
    "model": "Honda Civic",
    "kind": "现代汽车",
    "titleZh": "本田 Honda Civic",
    "titleEn": "Honda Honda Civic",
    "descZh": "本田 Honda Civic 在全球累计销量 约 27,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Honda Civic  is a series of automobiles manufactured by Honda since 1972.",
    "production": 27000000,
    "salesUnits": 27000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Honda_Civic_e-HEV_Sport_%28XI%29_%E2%80%93_f_30062024.jpg/330px-Honda_Civic_e-HEV_Sport_%28XI%29_%E2%80%93_f_30062024.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Honda_Civic"
  },
  {
    "id": "brand-best-022",
    "year": 1990,
    "country": "多国",
    "brand": "Hyundai Motor Company",
    "model": "Hyundai Elantra",
    "kind": "现代汽车",
    "titleZh": "Hyundai Motor Company Hyundai Elantra",
    "titleEn": "Hyundai Motor Company Hyundai Elantra",
    "descZh": "Hyundai Motor Company Hyundai Elantra 在全球累计销量 约 14,400,000 台。主要装配地：South Korea: UlsanIndonesia: Bekasi。",
    "descEn": "The Hyundai Elantra, also known as the Hyundai Avante, is a series of compact cars produced by the South Korean manufacturer Hyundai since 1990..",
    "production": 14400000,
    "salesUnits": 14400000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "South Korea: UlsanIndonesia: Bekasi",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Hyundai_Avante_CN7_white_%2810%29_%28cropped%29.jpg/330px-Hyundai_Avante_CN7_white_%2810%29_%28cropped%29.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Hyundai_Elantra"
  },
  {
    "id": "brand-best-023",
    "year": 1968,
    "country": "多国",
    "brand": "Jaguar Cars",
    "model": "Jaguar XJ",
    "kind": "豪华车",
    "titleZh": "Jaguar Cars Jaguar XJ",
    "titleEn": "Jaguar Cars Jaguar XJ",
    "descZh": "Jaguar Cars Jaguar XJ 在全球累计销量 约 800,000 台。主要装配地：United Kingdom: Coventry, England。",
    "descEn": "The Jaguar XJ is a series of mid-size/full-size luxury cars produced by British automobile manufacturer Jaguar Cars from 1968 to 2019.",
    "production": 800000,
    "salesUnits": 800000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "United Kingdom: Coventry, England",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Jaguar_XJ_vs._Jetman_-_World-First_Desert_Drag_Race_%2822928441043%29_%28cropped%29.jpg/330px-Jaguar_XJ_vs._Jetman_-_World-First_Desert_Drag_Race_%2822928441043%29_%28cropped%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Jaguar_XJ"
  },
  {
    "id": "brand-best-024",
    "year": 1986,
    "country": "美国",
    "brand": "Jeep",
    "model": "Jeep Wrangler",
    "kind": "SUV",
    "titleZh": "Jeep Jeep Wrangler",
    "titleEn": "Jeep Jeep Wrangler",
    "descZh": "Jeep Jeep Wrangler 在全球累计销量 约 5,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Jeep Wrangler is a series of compact and mid-size off-road SUVs manufactured by Jeep since 1986, and currently in its fourth generation.",
    "production": 5000000,
    "salesUnits": 5000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/2018_Jeep_Wrangler_Sahara_Unlimited_Multijet_2.1_Front.jpg/330px-2018_Jeep_Wrangler_Sahara_Unlimited_Multijet_2.1_Front.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Jeep_Wrangler"
  },
  {
    "id": "brand-best-026",
    "year": 1980,
    "country": "俄罗斯",
    "brand": "拉达",
    "model": "Lada Riva",
    "kind": "轿车",
    "titleZh": "拉达 Lada Riva",
    "titleEn": "Lada Lada Riva",
    "descZh": "拉达 Lada Riva 在全球累计销量 约 13,500,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Lada / VAZ-2105, 2104 and 2107, collectively marketed as Lada Riva for right-hand drive models, the Lada Nova in Germany, and by multiple other names and markets, are a series of compact sedans of the Zhiguli line-up, built by Russian car manufacturer AvtoVAZ.",
    "production": 13500000,
    "salesUnits": 13500000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lada_2107_aka_Lada_Riva_October_1995_1452cc.jpg/330px-Lada_2107_aka_Lada_Riva_October_1995_1452cc.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Lada_Riva"
  },
  {
    "id": "brand-best-027",
    "year": 2018,
    "country": "意大利",
    "brand": "兰博基尼",
    "model": "Lamborghini Urus",
    "kind": "SUV",
    "titleZh": "兰博基尼 Lamborghini Urus",
    "titleEn": "Lamborghini Lamborghini Urus",
    "descZh": "兰博基尼 Lamborghini Urus 在全球累计销量 约 20,000 台。主要装配地：Italy: Sant'Agata Bolognese。",
    "descEn": "The Lamborghini Urus is a high performance luxury SUV manufactured by Italian automobile manufacturer Lamborghini.",
    "production": 20000,
    "salesUnits": 20000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Italy: Sant'Agata Bolognese",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Lamborghini_Urus_SE_DSC_8524.jpg/330px-Lamborghini_Urus_SE_DSC_8524.jpg",
    "policyScore": 10,
    "policyTagsZh": [
      "欧盟单一市场扩大规模化销售"
    ],
    "source": "https://en.wikipedia.org/wiki/Lamborghini_Urus"
  },
  {
    "id": "brand-best-028",
    "year": 1996,
    "country": "意大利",
    "brand": "蓝旗亚",
    "model": "Lancia Ypsilon",
    "kind": "现代汽车",
    "titleZh": "蓝旗亚 Lancia Ypsilon",
    "titleEn": "Lancia Lancia Ypsilon",
    "descZh": "蓝旗亚 Lancia Ypsilon 在全球累计销量 约 870,000 台。主要装配地：Italy: Melfi。",
    "descEn": "The Lancia Ypsilon is a supermini car manufactured and marketed by Lancia, currently in its fourth generation and as of 2024, the marque's only model.",
    "production": 870000,
    "salesUnits": 870000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Italy: Melfi",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Lancia_Ypsilon_%282024%29_Front_1_%28cropped%29_%28cropped%29.jpg/330px-Lancia_Ypsilon_%282024%29_Front_1_%28cropped%29_%28cropped%29.jpg",
    "policyScore": 10,
    "policyTagsZh": [
      "欧盟单一市场扩大规模化销售"
    ],
    "source": "https://en.wikipedia.org/wiki/Lancia_Ypsilon"
  },
  {
    "id": "brand-best-029",
    "year": 1948,
    "country": "英国",
    "brand": "路虎",
    "model": "Land Rover Series",
    "kind": "电动车",
    "titleZh": "路虎 Land Rover Series",
    "titleEn": "Land Rover Land Rover Series",
    "descZh": "路虎 Land Rover Series 在全球累计销量 约 2,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Land Rover Series I, II, and III, or simply the Land-Rover are compact British off-road vehicles, produced by the Rover Company since 1948, and later by British Leyland.",
    "production": 2000000,
    "salesUnits": 2000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Land_Rover_Series_I_1948_%28HUE_166%29.jpg/330px-Land_Rover_Series_I_1948_%28HUE_166%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Land_Rover_Series"
  },
  {
    "id": "brand-best-030",
    "year": 1981,
    "country": "美国",
    "brand": "林肯",
    "model": "Lincoln Town Car",
    "kind": "电动车",
    "titleZh": "林肯 Lincoln Town Car",
    "titleEn": "Lincoln Lincoln Town Car",
    "descZh": "林肯 Lincoln Town Car 在全球累计销量 约 2,290,000 台。主要装配地：United States: Wixom, Michigan (Wixom Assembly Plant)。",
    "descEn": "The Lincoln Town Car is a model line of full-size luxury sedans that was marketed and produced by the Lincoln division of the American automaker Ford Motor Company.",
    "production": 2290000,
    "salesUnits": 2290000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "United States: Wixom, Michigan (Wixom Assembly Plant)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Lincoln_Town_Car_%282003-2008%29%2C_front_left.jpg/330px-Lincoln_Town_Car_%282003-2008%29%2C_front_left.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Lincoln_Town_Car"
  },
  {
    "id": "brand-best-031",
    "year": 1996,
    "country": "多国",
    "brand": "Lotus Cars",
    "model": "Lotus Elise",
    "kind": "跑车",
    "titleZh": "Lotus Cars Lotus Elise",
    "titleEn": "Lotus Cars Lotus Elise",
    "descZh": "Lotus Cars Lotus Elise 在全球累计销量 约 3,400 台。主要装配地：United Kingdom: Hethel, Norfolk, EnglandMalaysia: Shah Alam (Lotus Cars Malaysia: Series 1, 1997&ndash;2000)。",
    "descEn": "The Lotus Elise is a sports car conceived in early 1994 and released in September 1996 by the British manufacturer Lotus Cars.",
    "production": 3400,
    "salesUnits": 3400,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "United Kingdom: Hethel, Norfolk, EnglandMalaysia: Shah Alam (Lotus Cars Malaysia: Series 1, 1997&ndash;2000)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lotus_Elise_Club_Racer_%28front_quarter%29.jpg/330px-Lotus_Elise_Club_Racer_%28front_quarter%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Lotus_Elise"
  },
  {
    "id": "brand-best-032",
    "year": 2007,
    "country": "多国",
    "brand": "Maserati",
    "model": "Maserati GranTurismo",
    "kind": "现代汽车",
    "titleZh": "Maserati Maserati GranTurismo",
    "titleEn": "Maserati Maserati GranTurismo",
    "descZh": "Maserati Maserati GranTurismo 在全球累计销量 约 40,250 台。主要装配地：Italy: Modena。",
    "descEn": "The Maserati GranTurismo and GranCabrio are a series of grand tourers produced by the Italian manufacturer Maserati, succeeding the Maserati Coupé and Spyder..",
    "production": 40250,
    "salesUnits": 40250,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Italy: Modena",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Maserati_GranTurismo_Trofeo_1X7A0828.jpg/330px-Maserati_GranTurismo_Trofeo_1X7A0828.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Maserati_GranTurismo"
  },
  {
    "id": "brand-best-033",
    "year": 1963,
    "country": "日本",
    "brand": "马自达",
    "model": "Mazda Familia",
    "kind": "现代汽车",
    "titleZh": "马自达 Mazda Familia",
    "titleEn": "Mazda Mazda Familia",
    "descZh": "马自达 Mazda Familia 在全球累计销量 约 10,000,000 台。主要装配地：Japan: Hiroshima Assembly, Hiroshima。",
    "descEn": "The Mazda Familia , also marketed prominently as the Mazda 323, Mazda Protegé and Mazda Allegro, is a small family car that was manufactured by Mazda between 1963 and 2003.",
    "production": 10000000,
    "salesUnits": 10000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Japan: Hiroshima Assembly, Hiroshima",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/2003_Mazda_323_%28BJ_II%29_Proteg%C3%A9_Shades_sedan_%282015-08-07%29_01.jpg/330px-2003_Mazda_323_%28BJ_II%29_Proteg%C3%A9_Shades_sedan_%282015-08-07%29_01.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Mazda_Familia"
  },
  {
    "id": "brand-best-034",
    "year": 1993,
    "country": "德国",
    "brand": "梅赛德斯-奔驰",
    "model": "Mercedes-Benz C-Class",
    "kind": "豪华车",
    "titleZh": "梅赛德斯-奔驰 Mercedes-Benz C-Class",
    "titleEn": "Mercedes-Benz Mercedes-Benz C-Class",
    "descZh": "梅赛德斯-奔驰 Mercedes-Benz C-Class 在全球累计销量 约 6,900,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Mercedes-Benz C-Class is a series of compact executive cars produced by Mercedes-Benz Group AG.",
    "production": 6900000,
    "salesUnits": 6900000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Mercedes-Benz_W206_IMG_6380.jpg/330px-Mercedes-Benz_W206_IMG_6380.jpg",
    "policyScore": 10,
    "policyTagsZh": [
      "欧盟单一市场扩大规模化销售"
    ],
    "source": "https://en.wikipedia.org/wiki/Mercedes-Benz_C-Class"
  },
  {
    "id": "brand-best-035",
    "year": 1973,
    "country": "多国",
    "brand": "Mitsubishi Motors",
    "model": "Mitsubishi Lancer",
    "kind": "现代汽车",
    "titleZh": "Mitsubishi Motors Mitsubishi Lancer",
    "titleEn": "Mitsubishi Motors Mitsubishi Lancer",
    "descZh": "Mitsubishi Motors Mitsubishi Lancer 在全球累计销量 约 6,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Mitsubishi Lancer is an automobile that was produced by the Japanese manufacturer Mitsubishi Motors from 1973 until 2024..",
    "production": 6000000,
    "salesUnits": 6000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/2012_Mitsubishi_Lancer_SE_sedan_--_02-04-2012_2.jpg/330px-2012_Mitsubishi_Lancer_SE_sedan_--_02-04-2012_2.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Mitsubishi_Lancer"
  },
  {
    "id": "brand-best-036",
    "year": 1966,
    "country": "日本",
    "brand": "日产",
    "model": "Nissan Sunny",
    "kind": "现代汽车",
    "titleZh": "日产 Nissan Sunny",
    "titleEn": "Nissan Nissan Sunny",
    "descZh": "日产 Nissan Sunny 在全球累计销量 约 15,900,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Nissan Sunny  is an automobile built by the Japanese automaker Nissan from 1966 until 2004.",
    "production": 15900000,
    "salesUnits": 15900000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/NISSAN_Sunny_B13.jpg/330px-NISSAN_Sunny_B13.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Nissan_Sunny"
  },
  {
    "id": "brand-best-037",
    "year": 1982,
    "country": "德国",
    "brand": "欧宝",
    "model": "Opel Corsa",
    "kind": "电动车",
    "titleZh": "欧宝 Opel Corsa",
    "titleEn": "Opel Opel Corsa",
    "descZh": "欧宝 Opel Corsa 在全球累计销量 约 18,000,000 台。主要装配地：Spain: ZaragozaYugoslavia: Kikinda (IDA-Opel)。",
    "descEn": "The Opel Corsa is a supermini car manufactured and marketed by Opel since 1982.",
    "production": 18000000,
    "salesUnits": 18000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Spain: ZaragozaYugoslavia: Kikinda (IDA-Opel)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Opel_Corsa-e_at_IAA_2019_IMG_0738.jpg/330px-Opel_Corsa-e_at_IAA_2019_IMG_0738.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Opel_Corsa"
  },
  {
    "id": "brand-best-038",
    "year": 2005,
    "country": "多国",
    "brand": "Perodua",
    "model": "Perodua Myvi",
    "kind": "电动车",
    "titleZh": "Perodua Perodua Myvi",
    "titleEn": "Perodua Perodua Myvi",
    "descZh": "Perodua Perodua Myvi 在全球累计销量 约 1,400,000 台。主要装配地：Malaysia: Rawang, Selangor (PMSB)。",
    "descEn": "The Perodua Myvi is a subcompact car/supermini (B-segment) produced by the Malaysian manufacturer Perodua since 2005.",
    "production": 1400000,
    "salesUnits": 1400000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Malaysia: Rawang, Selangor (PMSB)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/2013_Perodua_Myvi_1.3_SE_%28S-Series%29_in_Cyberjaya%2C_Malaysia_%2803%29.jpg/330px-2013_Perodua_Myvi_1.3_SE_%28S-Series%29_in_Cyberjaya%2C_Malaysia_%2803%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Perodua_Myvi"
  },
  {
    "id": "brand-best-039",
    "year": 1998,
    "country": "法国",
    "brand": "标致",
    "model": "Peugeot 206",
    "kind": "电动车",
    "titleZh": "标致 Peugeot 206",
    "titleEn": "Peugeot Peugeot 206",
    "descZh": "标致 Peugeot 206 在全球累计销量 约 10,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Peugeot 206 is a supermini car (B-segment) designed and produced by the French car manufacturer Peugeot since May 1998 as a replacement to the Peugeot 205.",
    "production": 10000000,
    "salesUnits": 10000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/2002_Peugeot_206_LX_1.4_Front.jpg/330px-2002_Peugeot_206_LX_1.4_Front.jpg",
    "policyScore": 10,
    "policyTagsZh": [
      "欧盟单一市场扩大规模化销售"
    ],
    "source": "https://en.wikipedia.org/wiki/Peugeot_206"
  },
  {
    "id": "brand-best-040",
    "year": 1963,
    "country": "德国",
    "brand": "保时捷",
    "model": "Porsche 911",
    "kind": "跑车",
    "titleZh": "保时捷 Porsche 911",
    "titleEn": "Porsche Porsche 911",
    "descZh": "保时捷 Porsche 911 在全球累计销量 约 1,000,000 台。主要装配地：Germany: Stuttgart, Baden-Württemberg。",
    "descEn": "The Porsche 911 model series is a family of two-door, high performance rear-engine sports cars, introduced in September 1964 by Porsche of Stuttgart, Germany, and now in its eighth generation.",
    "production": 1000000,
    "salesUnits": 1000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Germany: Stuttgart, Baden-Württemberg",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Porsche_911_No_1000000%2C_70_Years_Porsche_Sports_Car%2C_Berlin_%281X7A3888%29.jpg/330px-Porsche_911_No_1000000%2C_70_Years_Porsche_Sports_Car%2C_Berlin_%281X7A3888%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Porsche_911"
  },
  {
    "id": "brand-best-041",
    "year": 1985,
    "country": "多国",
    "brand": "PROTON Holdings",
    "model": "Proton Saga",
    "kind": "现代汽车",
    "titleZh": "PROTON Holdings Proton Saga",
    "titleEn": "PROTON Holdings Proton Saga",
    "descZh": "PROTON Holdings Proton Saga 在全球累计销量 约 1,900,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Proton Saga is a series of subcompact cars and currently city cars produced by Malaysian automobile manufacturer Proton.",
    "production": 1900000,
    "salesUnits": 1900000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Three_generations_of_Proton_Saga_%2830383928616%29.jpg/330px-Three_generations_of_Proton_Saga_%2830383928616%29.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Proton_Saga"
  },
  {
    "id": "brand-best-042",
    "year": 1990,
    "country": "法国",
    "brand": "雷诺",
    "model": "Renault Clio",
    "kind": "现代汽车",
    "titleZh": "雷诺 Renault Clio",
    "titleEn": "Renault Renault Clio",
    "descZh": "雷诺 Renault Clio 在全球累计销量 约 12,300,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Renault Clio is a supermini (B-segment) car, produced by French automobile manufacturer Renault.",
    "production": 12300000,
    "salesUnits": 12300000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Renault_Clio_%28V%2C_Facelift%29_%E2%80%93_f_02092025.jpg/330px-Renault_Clio_%28V%2C_Facelift%29_%E2%80%93_f_02092025.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Renault_Clio"
  },
  {
    "id": "brand-best-043",
    "year": 1965,
    "country": "多国",
    "brand": "Rolls-Royce Motors",
    "model": "Rolls-Royce Silver Shadow",
    "kind": "豪华车",
    "titleZh": "Rolls-Royce Motors Rolls-Royce Silver Shadow",
    "titleEn": "Rolls-Royce Motors Rolls-Royce Silver Shadow",
    "descZh": "Rolls-Royce Motors Rolls-Royce Silver Shadow 在全球累计销量 约 29,030 台。主要装配地：United Kingdom: Crewe, England。",
    "descEn": "The Rolls-Royce Silver Shadow and its slightly stretched version, the Rolls-Royce Silver Wraith II, are full-size luxury cars produced by British automaker Rolls-Royce in various forms from 1965 to 1980.",
    "production": 29030,
    "salesUnits": 29030,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "United Kingdom: Crewe, England",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Rolls_Royce_Silver_Shadow_%281971%29.jpg/330px-Rolls_Royce_Silver_Shadow_%281971%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Rolls-Royce_Silver_Shadow"
  },
  {
    "id": "brand-best-044",
    "year": 1984,
    "country": "西班牙",
    "brand": "西雅特",
    "model": "SEAT Ibiza",
    "kind": "电动车",
    "titleZh": "西雅特 SEAT Ibiza",
    "titleEn": "SEAT SEAT Ibiza",
    "descZh": "西雅特 SEAT Ibiza 在全球累计销量 约 3,949,597 台。主要装配地：Spain: Barcelona。",
    "descEn": "The SEAT Ibiza is a supermini car that has been manufactured by Spanish car manufacturer SEAT since 1984.",
    "production": 3949597,
    "salesUnits": 3949597,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Spain: Barcelona",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2018_SEAT_Ibiza_SE_Technology_MPi_1.0_Front.jpg/330px-2018_SEAT_Ibiza_SE_Technology_MPi_1.0_Front.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/SEAT_Ibiza"
  },
  {
    "id": "brand-best-045",
    "year": 1998,
    "country": "多国",
    "brand": "Smart",
    "model": "Smart Fortwo",
    "kind": "现代汽车",
    "titleZh": "Smart Smart Fortwo",
    "titleEn": "Smart Smart Fortwo",
    "descZh": "Smart Smart Fortwo 在全球累计销量 约 1,700,000 台。主要装配地：France: Hambach (Smartville)。",
    "descEn": "The Smart Fortwo is a two-seater city car manufactured and marketed by the Smart division of the Mercedes-Benz Group for model years 1998–2024, across three generations — each using a rear-engine, rear-wheel-drive layout and a one-box design..",
    "production": 1700000,
    "salesUnits": 1700000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "France: Hambach (Smartville)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/2016_Smart_Fortwo_Passion_Automatic_1.0_Front.jpg/330px-2016_Smart_Fortwo_Passion_Automatic_1.0_Front.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Smart_Fortwo"
  },
  {
    "id": "brand-best-046",
    "year": 1988,
    "country": "日本",
    "brand": "斯巴鲁",
    "model": "Subaru Legacy",
    "kind": "现代汽车",
    "titleZh": "斯巴鲁 Subaru Legacy",
    "titleEn": "Subaru Subaru Legacy",
    "descZh": "斯巴鲁 Subaru Legacy 在全球累计销量 约 3,600,000 台。主要装配地：Japan: Ōta, Gunma (Yajima plant; 1989–2020)United States: Lafayette, Indiana (Lafayette plant)。",
    "descEn": "The Subaru Legacy  is a mid-size car built by Japanese automobile manufacturer Subaru from 1989 to 2025.",
    "production": 3600000,
    "salesUnits": 3600000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Japan: Ōta, Gunma (Yajima plant; 1989–2020)United States: Lafayette, Indiana (Lafayette plant)",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/2020_Subaru_Legacy%2C_front_10.1.20.jpg/330px-2020_Subaru_Legacy%2C_front_10.1.20.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Subaru_Legacy"
  },
  {
    "id": "brand-best-047",
    "year": 1996,
    "country": "多国",
    "brand": "Škoda Auto",
    "model": "Škoda Octavia",
    "kind": "现代汽车",
    "titleZh": "Škoda Auto Škoda Octavia",
    "titleEn": "Škoda Auto Škoda Octavia",
    "descZh": "Škoda Auto Škoda Octavia 在全球累计销量 约 6,000,000 台。主要装配地：Mladá Boleslav, Czech RepublicPoznań, PolandSarajevo, Bosnia and HerzegovinaAurangabad, India (Škoda India)Solomonovo, U…。",
    "descEn": "The Škoda Octavia is a small family car (C-segment) produced by the Czech car manufacturer Škoda Auto since the end of 1996.",
    "production": 6000000,
    "salesUnits": 6000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "Mladá Boleslav, Czech RepublicPoznań, PolandSarajevo, Bosnia and HerzegovinaAurangabad, India (Škoda India)Solomonovo, U…",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Skoda_Octavia_IV_liftback_%28cropped%29.jpg/330px-Skoda_Octavia_IV_liftback_%28cropped%29.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Škoda_Octavia"
  },
  {
    "id": "brand-best-049",
    "year": 1966,
    "country": "日本",
    "brand": "丰田",
    "model": "Toyota Corolla",
    "kind": "现代汽车",
    "titleZh": "丰田 Toyota Corolla",
    "titleEn": "Toyota Toyota Corolla",
    "descZh": "丰田 Toyota Corolla 在全球累计销量 约 50,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Toyota Corolla  is a series of compact cars manufactured and marketed globally by the Japanese automaker Toyota Motor Corporation.",
    "production": 50000000,
    "salesUnits": 50000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Toyota_Corolla_Hybrid_%28E210%29_IMG_4338.jpg/330px-Toyota_Corolla_Hybrid_%28E210%29_IMG_4338.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Toyota_Corolla"
  },
  {
    "id": "brand-best-050",
    "year": 2020,
    "country": "多国",
    "brand": "Tesla, Inc.",
    "model": "Tesla Model Y",
    "kind": "电动车",
    "titleZh": "Tesla, Inc. Tesla Model Y",
    "titleEn": "Tesla, Inc. Tesla Model Y",
    "descZh": "Tesla, Inc. Tesla Model Y 在全球累计销量 约 2,160,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Tesla Model Y is a battery electric compact crossover SUV produced by Tesla, Inc.",
    "production": 2160000,
    "salesUnits": 2160000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/2023_Tesla_Model_Y_Long_Range_All-Wheel_Drive_in_Pearl_White_Multi-Coat%2C_front_right%2C_2024-09-25.jpg/330px-2023_Tesla_Model_Y_Long_Range_All-Wheel_Drive_in_Pearl_White_Multi-Coat%2C_front_right%2C_2024-09-25.jpg",
    "policyScore": 34,
    "policyTagsZh": [
      "新能源补贴与排放法规提升电动化需求"
    ],
    "source": "https://en.wikipedia.org/wiki/Tesla_Model_Y"
  },
  {
    "id": "brand-best-051",
    "year": 1974,
    "country": "德国",
    "brand": "大众",
    "model": "Volkswagen Golf",
    "kind": "现代汽车",
    "titleZh": "大众 Volkswagen Golf",
    "titleEn": "Volkswagen Volkswagen Golf",
    "descZh": "大众 Volkswagen Golf 在全球累计销量 约 35,000,000 台。主要装配地：装配地信息待补充。",
    "descEn": "The Volkswagen Golf is a compact car/small family car (C-segment) produced by the German automotive manufacturer Volkswagen since 1974, marketed worldwide across eight generations, in various body configurations and under various nameplates – including as the Volkswagen Rabbit in the United States and Canada, and as the Volkswagen Caribe in Mexico (Mk1).",
    "production": 35000000,
    "salesUnits": 35000000,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/2020_Volkswagen_Golf_Style_1.5_Front.jpg/330px-2020_Volkswagen_Golf_Style_1.5_Front.jpg",
    "policyScore": 18,
    "policyTagsZh": [
      "石油危机后节油法规推动紧凑车型"
    ],
    "source": "https://en.wikipedia.org/wiki/Volkswagen_Golf"
  },
  {
    "id": "brand-best-052",
    "year": 1974,
    "country": "瑞典",
    "brand": "沃尔沃",
    "model": "Volvo 200 Series",
    "kind": "电动车",
    "titleZh": "沃尔沃 Volvo 200 Series",
    "titleEn": "Volvo Volvo 200 Series",
    "descZh": "沃尔沃 Volvo 200 Series 在全球累计销量 约 2,862,573 台。主要装配地：装配地信息待补充。",
    "descEn": "The Volvo 200 Series was a range of mid-size cars manufactured by Swedish automaker Volvo Cars from 1974 to 1993.",
    "production": 2862573,
    "salesUnits": 2862573,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/1988-1991_Volvo_240_GL_station_wagon_%282011-06-15%29_01.jpg/330px-1988-1991_Volvo_240_GL_station_wagon_%282011-06-15%29_01.jpg",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Volvo_200_Series"
  },
  {
    "id": "brand-best-053",
    "year": 1960,
    "country": "多国",
    "brand": "ZAZ",
    "model": "Zaporozhets",
    "kind": "两厢车",
    "titleZh": "ZAZ Zaporozhets",
    "titleEn": "ZAZ Zaporozhets",
    "descZh": "ZAZ Zaporozhets 在全球累计销量 约 3,422,444 台。主要装配地：装配地信息待补充。",
    "descEn": "ZAZ Zaporozhets was a series of rear-wheel-drive superminis designed and built from 1958 at the ZAZ factory in Soviet Ukraine.",
    "production": 3422444,
    "salesUnits": 3422444,
    "priceOriginal": null,
    "goldEquivalent": null,
    "manufacturingSites": "装配地信息待补充",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/c4/ZAZ.png",
    "policyScore": 0,
    "policyTagsZh": [
      "该车型销量更多受产品力、定价和渠道能力驱动"
    ],
    "source": "https://en.wikipedia.org/wiki/Zaporozhets"
  }
];

window.POLICY_EVENTS = [
  {
    "id": "policy-1930-smoot-hawley",
    "year": 1930,
    "region": "美国",
    "titleZh": "斯姆特-霍利关税法",
    "titleEn": "Smoot-Hawley Tariff Act",
    "impact": -35,
    "descZh": "大幅提高进口关税，全球贸易收缩，汽车跨境销售受压。"
  },
  {
    "id": "policy-1973-oil-crisis",
    "year": 1973,
    "region": "全球",
    "titleZh": "第一次石油危机",
    "titleEn": "First Oil Crisis",
    "impact": -40,
    "descZh": "油价飙升，小排量与省油车型需求快速上升。"
  },
  {
    "id": "policy-1975-cafe",
    "year": 1975,
    "region": "美国",
    "titleZh": "CAFE燃油经济性法规",
    "titleEn": "U.S. CAFE Standards",
    "impact": 22,
    "descZh": "推动厂商优化油耗，小型车和高效率技术加速普及。"
  },
  {
    "id": "policy-1992-eu-single-market",
    "year": 1992,
    "region": "欧洲",
    "titleZh": "欧盟单一市场深化",
    "titleEn": "EU Single Market Deepening",
    "impact": 18,
    "descZh": "统一市场降低跨国销售阻力，欧洲车型规模化扩大。"
  },
  {
    "id": "policy-2009-cn-tax-cut",
    "year": 2009,
    "region": "中国",
    "titleZh": "中国小排量购置税下调",
    "titleEn": "China Small-Engine Tax Cut",
    "impact": 30,
    "descZh": "1.6L及以下车型税率下调，家用车销量明显提升。"
  },
  {
    "id": "policy-2009-us-cash-for-clunkers",
    "year": 2009,
    "region": "美国",
    "titleZh": "美国以旧换新刺激计划",
    "titleEn": "Cash for Clunkers",
    "impact": 16,
    "descZh": "短期拉动新车销量，促进高油耗旧车退出。"
  },
  {
    "id": "policy-2010-cn-nev-subsidy",
    "year": 2010,
    "region": "中国",
    "titleZh": "中国新能源补贴启动",
    "titleEn": "China NEV Subsidy Program",
    "impact": 34,
    "descZh": "纯电与插混市场快速放量，产业链同步扩张。"
  },
  {
    "id": "policy-2015-dieselgate",
    "year": 2015,
    "region": "欧洲/全球",
    "titleZh": "柴油排放事件后监管收紧",
    "titleEn": "Post-Dieselgate Regulation Tightening",
    "impact": -18,
    "descZh": "排放测试与合规成本上升，动力路线加速转向电动化。"
  },
  {
    "id": "policy-2020-eu-co2",
    "year": 2020,
    "region": "欧洲",
    "titleZh": "欧盟乘用车CO2目标收紧",
    "titleEn": "EU Fleet CO2 Targets Tightened",
    "impact": 26,
    "descZh": "推动欧洲车企加速推出电动车与混动车。"
  },
  {
    "id": "policy-2022-ira-us",
    "year": 2022,
    "region": "美国",
    "titleZh": "美国《通胀削减法案》电动车激励",
    "titleEn": "U.S. IRA EV Incentives",
    "impact": 28,
    "descZh": "税收抵免强化本土电动车和电池投资。"
  },
  {
    "id": "policy-2024-us-tariff-cn-ev",
    "year": 2024,
    "region": "美国/中国",
    "titleZh": "美国提高中国电动车关税",
    "titleEn": "U.S. Tariff Increase on China EVs",
    "impact": -30,
    "descZh": "部分跨境车型价格竞争力下降，出口结构受影响。"
  },
  {
    "id": "policy-2024-eu-ev-duties",
    "year": 2024,
    "region": "欧盟/中国",
    "titleZh": "欧盟对中国电动车临时反补贴税",
    "titleEn": "EU Provisional Duties on China EVs",
    "impact": -24,
    "descZh": "欧洲市场定价与本地化生产策略被迫调整。"
  }
];

window.TIMELINE_DATA = (window.TIMELINE_DATA || []).concat(window.BRAND_BESTSELLER_MODELS || []);
window.KINDS = Array.from(new Set([...(window.KINDS || []), "轿车", "两厢车", "豪华车", "SUV", "皮卡/卡车"]));
