window.TIMELINE_DATA = [
  {
    id: "wheel-origin",
    year: -3500,
    country: "美索不达米亚",
    brand: "人类文明",
    model: "实心木轮",
    kind: "文明里程碑",
    titleZh: "最早的轮子出现",
    titleEn: "The earliest wheel appears",
    descZh: "人类开始使用木轮，这是车辆、机械与交通革命的起点。",
    descEn: "Humans begin using wooden wheels, the starting point of vehicle technology.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "spoked-wheel",
    year: -2000,
    country: "埃及/西亚",
    brand: "人类文明",
    model: "辐条轮战车",
    kind: "文明里程碑",
    titleZh: "辐条轮与战车普及",
    titleEn: "Spoked wheels and chariots spread",
    descZh: "更轻的辐条轮让车辆速度大幅提升。",
    descEn: "Lighter spoked wheels significantly improve vehicle speed.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "roman-roads",
    year: -312,
    country: "古罗马",
    brand: "罗马工程",
    model: "阿庇亚大道体系",
    kind: "交通基础设施",
    titleZh: "罗马道路网络",
    titleEn: "Roman road network",
    descZh: "高质量道路让轮式运输的效率和覆盖范围大幅增长。",
    descEn: "High-quality roads expand the efficiency and reach of wheeled transport.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "qin-axle",
    year: -221,
    country: "中国",
    brand: "秦朝",
    model: "车同轨（统一轨距）",
    kind: "制度标准化",
    titleZh: "秦始皇统一轴距与车轨",
    titleEn: "Qin standardizes axle and track width",
    descZh: "统一标准提升道路兼容性，是交通标准化的重要案例。",
    descEn: "Unified standards improve road compatibility, a major step in transport standardization.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "cugnot-1769",
    year: 1769,
    country: "法国",
    brand: "N.-J. Cugnot",
    model: "Fardier à vapeur",
    kind: "蒸汽车辆",
    titleZh: "蒸汽三轮车实验",
    titleEn: "Steam tricycle experiment",
    descZh: "常被视为最早的自推进道路车辆原型之一。",
    descEn: "Often seen as one of the earliest self-propelled road vehicle prototypes.",
    production: 1,
    priceOriginal: "原型机（无公开统一售价）",
    goldEquivalent: null
  },
  {
    id: "trevithick-1804",
    year: 1804,
    country: "英国",
    brand: "Richard Trevithick",
    model: "蒸汽机车原型",
    kind: "铁路里程碑",
    titleZh: "蒸汽机车试跑",
    titleEn: "Steam locomotive trial run",
    descZh: "高压蒸汽机推动铁路运输进入工程实践阶段。",
    descEn: "High-pressure steam powers practical railway engineering.",
    production: 1,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "stockton-darlington",
    year: 1825,
    country: "英国",
    brand: "Stockton & Darlington Railway",
    model: "公共铁路运营",
    kind: "铁路里程碑",
    titleZh: "公共铁路时代开启",
    titleEn: "Public railway era begins",
    descZh: "铁路成为可规模化运营的交通系统。",
    descEn: "Rail becomes a scalable transport system.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "gauge-act-1846",
    year: 1846,
    country: "英国/欧洲",
    brand: "Gauge Act",
    model: "1435mm标准轨距扩散",
    kind: "制度标准化",
    titleZh: "欧洲标准轨距逐步统一",
    titleEn: "European standard gauge convergence",
    descZh: "标准化降低了跨区域运输成本，影响深远。",
    descEn: "Standardization lowers cross-region transport costs with lasting impact.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "lenoir-1860",
    year: 1860,
    country: "法国",
    brand: "Étienne Lenoir",
    model: "煤气内燃机",
    kind: "发动机技术",
    titleZh: "早期内燃机商业化",
    titleEn: "Early internal-combustion commercialization",
    descZh: "内燃机为现代汽车动力奠定路径。",
    descEn: "Internal combustion lays the path for modern cars.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "otto-1876",
    year: 1876,
    country: "德国",
    brand: "Nikolaus Otto",
    model: "四冲程奥托循环",
    kind: "发动机技术",
    titleZh: "四冲程循环成熟",
    titleEn: "Four-stroke cycle matures",
    descZh: "动力效率提升，成为后续汽油机核心方案。",
    descEn: "Efficiency improves and becomes the core gasoline engine principle.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "daimler-reitwagen",
    year: 1885,
    country: "德国",
    brand: "Daimler",
    model: "Reitwagen",
    kind: "内燃机车辆",
    titleZh: "高速汽油发动机上车",
    titleEn: "High-speed gasoline engine on vehicle",
    descZh: "被认为是摩托与轻型机动车的重要先驱。",
    descEn: "An important precursor for motorcycles and motor vehicles.",
    production: 1,
    priceOriginal: "原型机",
    goldEquivalent: null
  },
  {
    id: "benz-patent",
    year: 1886,
    country: "德国",
    brand: "Benz",
    model: "Patent-Motorwagen",
    kind: "现代汽车",
    titleZh: "专利汽车诞生",
    titleEn: "Patent motor car is born",
    descZh: "通常被视为现代汽车起点。",
    descEn: "Commonly regarded as the birth of the modern automobile.",
    production: 25,
    priceOriginal: "约 600 金马克",
    goldEquivalent: "约 215 克黄金（按金马克含金量估算）"
  },
  {
    id: "bertha-drive",
    year: 1888,
    country: "德国",
    brand: "Benz",
    model: "Patent-Motorwagen No.3",
    kind: "现代汽车",
    titleZh: "首次长途公路汽车行驶",
    titleEn: "First long-distance automobile trip",
    descZh: "贝尔塔·本茨长途驾驶证明汽车可用于真实出行。",
    descEn: "Bertha Benz proves cars can serve real-world travel.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "duryea-1892",
    year: 1892,
    country: "美国",
    brand: "Duryea",
    model: "Motor Wagon",
    kind: "现代汽车",
    titleZh: "美国早期汽油车",
    titleEn: "Early American gasoline car",
    descZh: "美国汽车工业起步阶段的代表车型。",
    descEn: "A representative model from the start of the U.S. auto industry.",
    production: 13,
    priceOriginal: "约 1,200 美元",
    goldEquivalent: "约 1,805 克黄金（按 1892 年金价估算）"
  },
  {
    id: "benz-velo",
    year: 1894,
    country: "德国",
    brand: "Benz",
    model: "Velo",
    kind: "现代汽车",
    titleZh: "最早量产车型之一",
    titleEn: "One of the first production cars",
    descZh: "标准化制造开始出现，汽车从实验品走向商品。",
    descEn: "Standardized manufacturing moves cars from prototypes to products.",
    production: 1200,
    priceOriginal: "约 2,000 金马克",
    goldEquivalent: "约 716 克黄金（按金马克含金量估算）"
  },
  {
    id: "renault-voiturette",
    year: 1898,
    country: "法国",
    brand: "Renault",
    model: "Voiturette",
    kind: "现代汽车",
    titleZh: "雷诺早期轻型车",
    titleEn: "Renault early light car",
    descZh: "法系汽车工业形成品牌化道路。",
    descEn: "French auto industry advances through branded products.",
    production: 381,
    priceOriginal: "约 3,000 法郎",
    goldEquivalent: "约 1,700 克黄金（粗略估算）"
  },
  {
    id: "fiat-35hp",
    year: 1899,
    country: "意大利",
    brand: "FIAT",
    model: "3½ HP",
    kind: "现代汽车",
    titleZh: "菲亚特起步车型",
    titleEn: "FIAT foundational model",
    descZh: "意大利汽车品牌进入工业化轨道。",
    descEn: "Italian auto branding enters industrial production.",
    production: 26,
    priceOriginal: "约 8,000 里拉",
    goldEquivalent: "约 900 克黄金（粗略估算）"
  },
  {
    id: "curved-dash-olds",
    year: 1900,
    country: "美国",
    brand: "Oldsmobile",
    model: "Curved Dash",
    kind: "现代汽车",
    titleZh: "早期大规模生产成功",
    titleEn: "Early mass-production success",
    descZh: "在福特之前已展示规模化制造潜力。",
    descEn: "Shows scalable car production before Ford's peak impact.",
    production: 19000,
    priceOriginal: "约 650 美元",
    goldEquivalent: "约 976 克黄金（按 1900 年金价估算）"
  },
  {
    id: "mercedes-35ps",
    year: 1901,
    country: "德国",
    brand: "Mercedes",
    model: "35 PS",
    kind: "现代汽车",
    titleZh: "现代车身布局雏形",
    titleEn: "Blueprint of modern vehicle layout",
    descZh: "低重心、长轴距设计接近现代汽车比例。",
    descEn: "Low center of gravity and long wheelbase foreshadow modern car proportions.",
    production: 36,
    priceOriginal: "约 16,000 金马克",
    goldEquivalent: "约 5,728 克黄金（按金马克含金量估算）"
  },
  {
    id: "lombard-track",
    year: 1901,
    country: "美国",
    brand: "Lombard",
    model: "Steam Log Hauler",
    kind: "履带车辆",
    titleZh: "履带车辆工程化",
    titleEn: "Tracked vehicle engineering",
    descZh: "早期履带动力平台，为后续坦克和工程车提供思路。",
    descEn: "An early tracked platform influencing tanks and engineering vehicles.",
    production: 83,
    priceOriginal: "约 3,000 美元",
    goldEquivalent: "约 4,504 克黄金（按 1901 年金价估算）"
  },
  {
    id: "ford-model-a-1903",
    year: 1903,
    country: "美国",
    brand: "Ford",
    model: "Model A (1903)",
    kind: "现代汽车",
    titleZh: "福特公司首款车型",
    titleEn: "Ford's first production model",
    descZh: "福特工业体系的起点。",
    descEn: "The beginning of Ford's industrial system.",
    production: 1750,
    priceOriginal: "约 750 美元",
    goldEquivalent: "约 1,126 克黄金（按 1903 年金价估算）"
  },
  {
    id: "holt-track-tractor",
    year: 1904,
    country: "美国",
    brand: "Holt",
    model: "Track-Type Tractor",
    kind: "履带车辆",
    titleZh: "履带拖拉机商业化",
    titleEn: "Tracked tractor commercialization",
    descZh: "履带技术从木材运输扩展到农业与军工。",
    descEn: "Tracked tech expands from logging to farming and military uses.",
    production: null,
    priceOriginal: "约 5,500 美元",
    goldEquivalent: "约 8,257 克黄金（按 1904 年金价估算）"
  },
  {
    id: "rolls-silver-ghost",
    year: 1906,
    country: "英国",
    brand: "Rolls-Royce",
    model: "Silver Ghost",
    kind: "现代汽车",
    titleZh: "豪华车标杆建立",
    titleEn: "Luxury benchmark established",
    descZh: "高可靠性和精工制造定义豪华车标准。",
    descEn: "Reliability and craftsmanship define luxury standards.",
    production: 7874,
    priceOriginal: "约 985 英镑",
    goldEquivalent: "约 7,211 克黄金（按当时英镑金本位估算）"
  },
  {
    id: "ford-model-t",
    year: 1908,
    country: "美国",
    brand: "Ford",
    model: "Model T",
    kind: "现代汽车",
    titleZh: "平民汽车时代",
    titleEn: "The age of affordable cars",
    descZh: "让普通家庭也能拥有汽车，重塑社会出行。",
    descEn: "Makes car ownership possible for ordinary families.",
    production: 15000000,
    priceOriginal: "首发约 850 美元",
    goldEquivalent: "约 1,279 克黄金（按 1908 年金价估算）"
  },
  {
    id: "chevrolet-classic-six",
    year: 1911,
    country: "美国",
    brand: "Chevrolet",
    model: "Classic Six",
    kind: "现代汽车",
    titleZh: "雪佛兰品牌诞生期",
    titleEn: "Chevrolet launch era",
    descZh: "美国多品牌竞争格局逐步形成。",
    descEn: "The U.S. multi-brand competitive landscape takes shape.",
    production: null,
    priceOriginal: "约 2,150 美元",
    goldEquivalent: "约 3,235 克黄金（按 1911 年金价估算）"
  },
  {
    id: "moving-assembly-1913",
    year: 1913,
    country: "美国",
    brand: "Ford",
    model: "移动装配线",
    kind: "制造技术",
    titleZh: "流水线革命",
    titleEn: "Moving assembly line revolution",
    descZh: "单车装配时间显著缩短，成本快速下降。",
    descEn: "Assembly time drops dramatically and costs fall quickly.",
    production: null,
    priceOriginal: null,
    goldEquivalent: null
  },
  {
    id: "mark-i-tank",
    year: 1916,
    country: "英国",
    brand: "Foster / Royal Navy Landships",
    model: "Mark I",
    kind: "坦克",
    titleZh: "首批坦克实战",
    titleEn: "First tanks in combat",
    descZh: "履带装甲车辆进入战争并影响后续军工车辆设计。",
    descEn: "Tracked armored vehicles enter combat and reshape military design.",
    production: 150,
    priceOriginal: "约 5,600 英镑",
    goldEquivalent: "约 41,000 克黄金（按当时英镑金本位估算）"
  },
  {
    id: "renault-ft",
    year: 1917,
    country: "法国",
    brand: "Renault",
    model: "FT",
    kind: "坦克",
    titleZh: "现代坦克布局成型",
    titleEn: "Modern tank layout emerges",
    descZh: "炮塔+发动机后置布局影响后世坦克设计。",
    descEn: "Turret-forward, engine-rear layout influences future tanks.",
    production: 3694,
    priceOriginal: "约 56,000 法郎",
    goldEquivalent: "约 16,000 克黄金（粗略估算）"
  },
  {
    id: "austin-seven",
    year: 1921,
    country: "英国",
    brand: "Austin",
    model: "Seven",
    kind: "现代汽车",
    titleZh: "英国国民小车",
    titleEn: "Britain's people's small car",
    descZh: "轻量与低价策略影响欧洲小车发展。",
    descEn: "Lightweight and low-price strategy shapes European compact cars.",
    production: 290000,
    priceOriginal: "约 225 英镑",
    goldEquivalent: "约 1,650 克黄金（按英镑金本位近似）"
  },
  {
    id: "chrysler-b70",
    year: 1924,
    country: "美国",
    brand: "Chrysler",
    model: "B-70",
    kind: "现代汽车",
    titleZh: "克莱斯勒品牌起步",
    titleEn: "Chrysler brand launch",
    descZh: "美国汽车工业进入更成熟的集团竞争。",
    descEn: "U.S. auto industry enters mature group competition.",
    production: 32000,
    priceOriginal: "约 1,565 美元",
    goldEquivalent: "约 2,353 克黄金（按 1924 年金价估算）"
  },
  {
    id: "ford-model-a-1927",
    year: 1927,
    country: "美国",
    brand: "Ford",
    model: "Model A (1927)",
    kind: "现代汽车",
    titleZh: "Model T 继任者",
    titleEn: "Successor to Model T",
    descZh: "在更高性能和舒适度上满足新一代消费者。",
    descEn: "Delivers better performance and comfort for new buyers.",
    production: 4800000,
    priceOriginal: "约 385 美元",
    goldEquivalent: "约 579 克黄金（按 1927 年金价估算）"
  },
  {
    id: "citroen-traction",
    year: 1934,
    country: "法国",
    brand: "Citroën",
    model: "Traction Avant",
    kind: "现代汽车",
    titleZh: "前轮驱动量产化",
    titleEn: "Front-wheel drive in mass production",
    descZh: "前驱、承载式车身等先进方案进入大众市场。",
    descEn: "FWD and monocoque ideas enter mainstream production.",
    production: 760000,
    priceOriginal: "约 26,900 法郎",
    goldEquivalent: "约 4,600 克黄金（粗略估算）"
  },
  {
    id: "mercedes-260d",
    year: 1936,
    country: "德国",
    brand: "Mercedes-Benz",
    model: "260 D",
    kind: "现代汽车",
    titleZh: "乘用车柴油化先驱",
    titleEn: "Pioneer diesel passenger car",
    descZh: "柴油发动机进入轿车市场。",
    descEn: "Diesel engines enter the passenger car market.",
    production: 1967,
    priceOriginal: "约 6,800 帝国马克",
    goldEquivalent: "约 2,435 克黄金（按马克含金近似）"
  },
  {
    id: "vw-beetle",
    year: 1938,
    country: "德国",
    brand: "Volkswagen",
    model: "Käfer (Beetle)",
    kind: "现代汽车",
    titleZh: "大众甲壳虫计划",
    titleEn: "Volkswagen Beetle program",
    descZh: "“国民车”理念影响全球汽车普及模式。",
    descEn: "The people's-car concept influences global motorization.",
    production: 21000000,
    priceOriginal: "约 990 帝国马克",
    goldEquivalent: "约 355 克黄金（按马克含金近似）"
  },
  {
    id: "t34-tank",
    year: 1940,
    country: "苏联",
    brand: "KhPZ / Uralvagonzavod",
    model: "T-34",
    kind: "坦克",
    titleZh: "经典中型坦克",
    titleEn: "Iconic medium tank",
    descZh: "斜面装甲与机动性成为经典战车设计范式。",
    descEn: "Sloped armor and mobility become a classic design pattern.",
    production: 84000,
    priceOriginal: "约 269,500 卢布（早期批次）",
    goldEquivalent: "约 20,000 克黄金（粗略估算）"
  },
  {
    id: "willys-mb",
    year: 1942,
    country: "美国",
    brand: "Willys",
    model: "MB Jeep",
    kind: "军用车辆",
    titleZh: "吉普成为越野符号",
    titleEn: "Jeep becomes an off-road icon",
    descZh: "高机动轻型军车影响战后民用越野车。",
    descEn: "Highly mobile military light vehicles influence post-war SUVs.",
    production: 640000,
    priceOriginal: "约 738 美元",
    goldEquivalent: "约 658 克黄金（按 1942 年金价估算）"
  },
  {
    id: "m4-sherman",
    year: 1942,
    country: "美国",
    brand: "U.S. Ordnance",
    model: "M4 Sherman",
    kind: "坦克",
    titleZh: "工业化大规模坦克",
    titleEn: "Industrial-scale tank production",
    descZh: "体现美国战时制造体系的规模能力。",
    descEn: "Represents U.S. wartime manufacturing at scale.",
    production: 49234,
    priceOriginal: "约 44,556 美元",
    goldEquivalent: "约 39,700 克黄金（按 1942 年金价估算）"
  },
  {
    id: "landrover-series1",
    year: 1948,
    country: "英国",
    brand: "Land Rover",
    model: "Series I",
    kind: "越野车",
    titleZh: "民用越野车模板",
    titleEn: "Template for civilian off-roaders",
    descZh: "工具属性强，奠定多功能越野车路线。",
    descEn: "Utility-first design sets the path for multi-purpose off-road vehicles.",
    production: 220000,
    priceOriginal: "约 450 英镑",
    goldEquivalent: "约 3,900 克黄金（粗略估算）"
  },
  {
    id: "porsche-356",
    year: 1948,
    country: "德国",
    brand: "Porsche",
    model: "356",
    kind: "跑车",
    titleZh: "保时捷品牌起点",
    titleEn: "Starting point of Porsche brand",
    descZh: "轻量化与操控导向成为保时捷基因。",
    descEn: "Lightweight handling-first philosophy becomes Porsche DNA.",
    production: 76000,
    priceOriginal: "约 10,000 德国马克",
    goldEquivalent: "约 2,500 克黄金（粗略估算）"
  },
  {
    id: "citroen-ds",
    year: 1955,
    country: "法国",
    brand: "Citroën",
    model: "DS",
    kind: "现代汽车",
    titleZh: "设计与底盘技术突破",
    titleEn: "Breakthrough in design and chassis tech",
    descZh: "空气动力外形与液压系统非常超前。",
    descEn: "Aerodynamic shape and hydraulic systems were far ahead of time.",
    production: 1455958,
    priceOriginal: "约 94 万旧法郎",
    goldEquivalent: "约 2,500 克黄金（粗略估算）"
  },
  {
    id: "fiat-500",
    year: 1957,
    country: "意大利",
    brand: "FIAT",
    model: "500",
    kind: "现代汽车",
    titleZh: "欧洲城市小车代表",
    titleEn: "European city-car icon",
    descZh: "小排量、低成本，推动欧洲家庭汽车化。",
    descEn: "Small engines and low cost drive family motorization in Europe.",
    production: 3800000,
    priceOriginal: "约 465,000 里拉",
    goldEquivalent: "约 1,900 克黄金（粗略估算）"
  },
  {
    id: "mini-1959",
    year: 1959,
    country: "英国",
    brand: "BMC",
    model: "Mini",
    kind: "现代汽车",
    titleZh: "横置前驱空间革命",
    titleEn: "Transverse FWD packaging revolution",
    descZh: "紧凑车内空间设计影响几十年小车布局。",
    descEn: "Its packaging influences small-car design for decades.",
    production: 5387000,
    priceOriginal: "约 496 英镑",
    goldEquivalent: "约 3,400 克黄金（粗略估算）"
  },
  {
    id: "mustang-1964",
    year: 1964,
    country: "美国",
    brand: "Ford",
    model: "Mustang",
    kind: "跑车",
    titleZh: "肌肉车文化爆发",
    titleEn: "Muscle-car culture takes off",
    descZh: "高性价比性能车塑造青年汽车文化。",
    descEn: "Affordable performance reshapes youth car culture.",
    production: 10000000,
    priceOriginal: "首发约 2,368 美元",
    goldEquivalent: "约 2,102 克黄金（按 1964 年金价估算）"
  },
  {
    id: "toyota-corolla",
    year: 1966,
    country: "日本",
    brand: "Toyota",
    model: "Corolla",
    kind: "现代汽车",
    titleZh: "全球销量冠军车型线",
    titleEn: "Global best-selling model line",
    descZh: "可靠、经济、易维护，成为全球家用车标杆。",
    descEn: "Reliable, economical, and easy to maintain, a global family-car benchmark.",
    production: 50000000,
    priceOriginal: "约 432,000 日元（初代）",
    goldEquivalent: "约 1,300 克黄金（粗略估算）"
  },
  {
    id: "nissan-sunny",
    year: 1967,
    country: "日本",
    brand: "Nissan",
    model: "Sunny B10",
    kind: "现代汽车",
    titleZh: "日系紧凑家轿扩张",
    titleEn: "Expansion of Japanese compact sedans",
    descZh: "日本品牌在全球中端市场快速增长。",
    descEn: "Japanese brands rapidly grow in the global mid-market.",
    production: 500000,
    priceOriginal: "约 410,000 日元",
    goldEquivalent: "约 1,250 克黄金（粗略估算）"
  },
  {
    id: "vw-golf",
    year: 1974,
    country: "德国",
    brand: "Volkswagen",
    model: "Golf",
    kind: "现代汽车",
    titleZh: "两厢家用车经典",
    titleEn: "Classic hatchback family car",
    descZh: "接替甲壳虫，定义现代两厢车体验。",
    descEn: "Succeeds the Beetle and defines modern hatchback driving.",
    production: 37000000,
    priceOriginal: "约 7,995 德国马克",
    goldEquivalent: "约 2,300 克黄金（粗略估算）"
  },
  {
    id: "g-class-1978",
    year: 1978,
    country: "德国",
    brand: "Mercedes-Benz",
    model: "G-Class",
    kind: "越野车",
    titleZh: "硬派越野长期进化",
    titleEn: "Long evolution of hardcore off-roaders",
    descZh: "从军用需求走向豪华越野市场。",
    descEn: "Moves from military roots to premium off-road segment.",
    production: 500000,
    priceOriginal: "约 48,000 德国马克",
    goldEquivalent: "约 10,500 克黄金（粗略估算）"
  },
  {
    id: "ferrari-testarossa",
    year: 1984,
    country: "意大利",
    brand: "Ferrari",
    model: "Testarossa",
    kind: "跑车",
    titleZh: "80年代超级跑车符号",
    titleEn: "1980s supercar symbol",
    descZh: "高性能与视觉设计共同定义时代审美。",
    descEn: "Performance and visual design define an era.",
    production: 7177,
    priceOriginal: "约 181,000 美元",
    goldEquivalent: "约 9,160 克黄金（按 1984 年金价估算）"
  },
  {
    id: "mazda-mx5",
    year: 1989,
    country: "日本",
    brand: "Mazda",
    model: "MX-5 Miata",
    kind: "跑车",
    titleZh: "轻量敞篷复兴",
    titleEn: "Lightweight roadster revival",
    descZh: "驾驶乐趣导向的小跑车全球热卖。",
    descEn: "Driver-focused roadsters gain worldwide popularity.",
    production: 1200000,
    priceOriginal: "首发约 13,999 美元",
    goldEquivalent: "约 1,167 克黄金（按 1989 年金价估算）"
  },
  {
    id: "mclaren-f1",
    year: 1994,
    country: "英国",
    brand: "McLaren",
    model: "F1",
    kind: "跑车",
    titleZh: "三座布局传奇超跑",
    titleEn: "Legendary three-seat supercar",
    descZh: "极限性能与工程轻量化里程碑。",
    descEn: "A milestone of extreme performance and lightweight engineering.",
    production: 106,
    priceOriginal: "约 540,000 英镑",
    goldEquivalent: "约 60,000 克黄金（粗略估算）"
  },
  {
    id: "toyota-prius",
    year: 1997,
    country: "日本",
    brand: "Toyota",
    model: "Prius",
    kind: "混动车",
    titleZh: "量产混动时代开启",
    titleEn: "Mass-market hybrid era begins",
    descZh: "混合动力从技术样机走向全球市场。",
    descEn: "Hybrid systems move from demo tech to global market.",
    production: 5000000,
    priceOriginal: "约 2,150,000 日元",
    goldEquivalent: "约 5,800 克黄金（粗略估算）"
  },
  {
    id: "smart-fortwo",
    year: 1998,
    country: "德国",
    brand: "Smart",
    model: "Fortwo",
    kind: "现代汽车",
    titleZh: "超小型城市车",
    titleEn: "Ultra-compact city car",
    descZh: "极短车身应对高密度城市停车需求。",
    descEn: "Very short body targets dense-city parking needs.",
    production: 1900000,
    priceOriginal: "约 18,750 德国马克",
    goldEquivalent: "约 4,300 克黄金（粗略估算）"
  },
  {
    id: "byd-f3",
    year: 2005,
    country: "中国",
    brand: "BYD",
    model: "F3",
    kind: "现代汽车",
    titleZh: "中国自主品牌上量",
    titleEn: "Chinese self-owned brands scale up",
    descZh: "国产乘用车进入大规模家庭市场。",
    descEn: "Chinese domestic passenger cars enter large family markets.",
    production: 2800000,
    priceOriginal: "约 73,800 元人民币",
    goldEquivalent: "约 1,700 克黄金（粗略估算）"
  },
  {
    id: "tesla-roadster",
    year: 2008,
    country: "美国",
    brand: "Tesla",
    model: "Roadster",
    kind: "电动车",
    titleZh: "现代高性能电动车开端",
    titleEn: "Start of modern high-performance EVs",
    descZh: "证明纯电跑车具备高性能潜力。",
    descEn: "Shows pure EV sports cars can deliver strong performance.",
    production: 2450,
    priceOriginal: "约 109,000 美元",
    goldEquivalent: "约 7,686 克黄金（按 2008 年金价估算）"
  },
  {
    id: "nissan-leaf",
    year: 2010,
    country: "日本",
    brand: "Nissan",
    model: "Leaf",
    kind: "电动车",
    titleZh: "全球主流纯电家轿",
    titleEn: "Mainstream global EV hatchback",
    descZh: "纯电车首次在大众市场形成持续销量。",
    descEn: "EVs achieve sustained sales in the mass market.",
    production: 650000,
    priceOriginal: "约 32,780 美元",
    goldEquivalent: "约 833 克黄金（按 2010 年金价估算）"
  },
  {
    id: "tesla-model-s",
    year: 2012,
    country: "美国",
    brand: "Tesla",
    model: "Model S",
    kind: "电动车",
    titleZh: "高端纯电轿车标杆",
    titleEn: "Benchmark premium EV sedan",
    descZh: "软件定义汽车和OTA升级概念加速普及。",
    descEn: "Software-defined vehicle and OTA ideas spread rapidly.",
    production: 550000,
    priceOriginal: "约 57,400 美元",
    goldEquivalent: "约 1,014 克黄金（按 2012 年金价估算）"
  },
  {
    id: "bmw-i3",
    year: 2013,
    country: "德国",
    brand: "BMW",
    model: "i3",
    kind: "电动车",
    titleZh: "碳纤维电动车尝试",
    titleEn: "Carbon-fiber EV experiment",
    descZh: "新材料与城市电动车路线结合。",
    descEn: "Combines new materials with urban EV design.",
    production: 250000,
    priceOriginal: "约 41,350 美元",
    goldEquivalent: "约 775 克黄金（按 2013 年金价估算）"
  },
  {
    id: "byd-qin",
    year: 2014,
    country: "中国",
    brand: "BYD",
    model: "秦",
    kind: "混动车",
    titleZh: "插混在中国快速普及",
    titleEn: "PHEVs scale quickly in China",
    descZh: "插混路线成为新能源过渡阶段关键方案。",
    descEn: "Plug-in hybrids become key in the transition phase.",
    production: 230000,
    priceOriginal: "约 189,800 元人民币",
    goldEquivalent: "约 3,100 克黄金（粗略估算）"
  },
  {
    id: "tesla-model3",
    year: 2016,
    country: "美国",
    brand: "Tesla",
    model: "Model 3",
    kind: "电动车",
    titleZh: "电动车进入大规模平价区",
    titleEn: "EVs enter large-scale affordable range",
    descZh: "纯电动车销量进入百万级平台。",
    descEn: "EV volumes rise to multi-million scale.",
    production: 3000000,
    priceOriginal: "约 35,000 美元",
    goldEquivalent: "约 882 克黄金（按 2016 年金价估算）"
  },
  {
    id: "nio-es8",
    year: 2017,
    country: "中国",
    brand: "NIO",
    model: "ES8",
    kind: "电动车",
    titleZh: "中国高端智能电动SUV",
    titleEn: "Chinese premium smart electric SUV",
    descZh: "换电和智能座舱成为差异化方向。",
    descEn: "Battery swapping and smart cockpit become differentiators.",
    production: 170000,
    priceOriginal: "约 448,000 元人民币",
    goldEquivalent: "约 6,700 克黄金（粗略估算）"
  },
  {
    id: "porsche-taycan",
    year: 2019,
    country: "德国",
    brand: "Porsche",
    model: "Taycan",
    kind: "电动车",
    titleZh: "性能豪华纯电化",
    titleEn: "Performance luxury goes electric",
    descZh: "传统豪华性能品牌全面切入纯电。",
    descEn: "A legacy performance luxury brand fully enters EVs.",
    production: 170000,
    priceOriginal: "约 103,800 美元",
    goldEquivalent: "约 1,478 克黄金（按 2019 年金价估算）"
  },
  {
    id: "wuling-mini-ev",
    year: 2020,
    country: "中国",
    brand: "五菱",
    model: "宏光 MINI EV",
    kind: "电动车",
    titleZh: "超低门槛电动车爆发",
    titleEn: "Ultra-affordable EV boom",
    descZh: "小型纯电车带来更低购车门槛。",
    descEn: "Mini EVs lower the cost barrier for first-time buyers.",
    production: 1400000,
    priceOriginal: "约 28,800 元人民币",
    goldEquivalent: "约 420 克黄金（粗略估算）"
  },
  {
    id: "lucid-air",
    year: 2021,
    country: "美国",
    brand: "Lucid",
    model: "Air",
    kind: "电动车",
    titleZh: "超长续航豪华纯电",
    titleEn: "Long-range luxury EV",
    descZh: "高效率电驱系统推动续航上限。",
    descEn: "High-efficiency electric drive pushes range limits.",
    production: 15000,
    priceOriginal: "约 77,400 美元",
    goldEquivalent: "约 1,375 克黄金（按 2021 年金价估算）"
  },
  {
    id: "rivian-r1t",
    year: 2022,
    country: "美国",
    brand: "Rivian",
    model: "R1T",
    kind: "电动皮卡",
    titleZh: "电动皮卡量产",
    titleEn: "Electric pickup reaches production",
    descZh: "电动化从轿车SUV扩展到工具型车辆。",
    descEn: "Electrification expands from sedans/SUVs to utility vehicles.",
    production: 70000,
    priceOriginal: "约 73,000 美元",
    goldEquivalent: "约 1,190 克黄金（按 2022 年金价估算）"
  },
  {
    id: "byd-seagull",
    year: 2023,
    country: "中国",
    brand: "BYD",
    model: "海鸥",
    kind: "电动车",
    titleZh: "A00级电动车全球关注",
    titleEn: "A00-segment EV gets global attention",
    descZh: "以极高性价比推动城市通勤电动化。",
    descEn: "Strong value proposition accelerates urban EV adoption.",
    production: 700000,
    priceOriginal: "约 73,800 元人民币",
    goldEquivalent: "约 980 克黄金（粗略估算）"
  },
  {
    id: "tesla-cybertruck",
    year: 2023,
    country: "美国",
    brand: "Tesla",
    model: "Cybertruck",
    kind: "电动皮卡",
    titleZh: "不锈钢电动皮卡量产交付",
    titleEn: "Stainless-steel electric pickup deliveries",
    descZh: "外形和制造方案都非常激进。",
    descEn: "Both styling and manufacturing approach are highly radical.",
    production: 50000,
    priceOriginal: "约 60,990 美元",
    goldEquivalent: "约 978 克黄金（按 2023 年金价估算）"
  },
  {
    id: "xiaomi-su7",
    year: 2024,
    country: "中国",
    brand: "小米",
    model: "SU7",
    kind: "电动车",
    titleZh: "消费电子企业进入汽车赛道",
    titleEn: "Consumer electronics company enters auto market",
    descZh: "智能生态与汽车深度融合成为新趋势。",
    descEn: "Deep integration between digital ecosystem and vehicles becomes a trend.",
    production: 135000,
    priceOriginal: "约 215,900 元人民币",
    goldEquivalent: "约 2,900 克黄金（粗略估算）"
  }
];

window.KINDS = [
  "文明里程碑",
  "交通基础设施",
  "制度标准化",
  "蒸汽车辆",
  "铁路里程碑",
  "发动机技术",
  "内燃机车辆",
  "现代汽车",
  "履带车辆",
  "制造技术",
  "坦克",
  "军用车辆",
  "越野车",
  "跑车",
  "混动车",
  "电动车",
  "电动皮卡"
];
