window.EARTH_BIO_EVENTS = [
  {
    id: "bio-cambrian",
    year: -541000000,
    domain: "bio",
    category: "海洋生物",
    titleZh: "寒武纪生命大爆发",
    titleEn: "Cambrian Explosion",
    descZh: "多细胞复杂生物快速出现，海洋食物网开始成形。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Anomalocaris_NMNS.jpg/320px-Anomalocaris_NMNS.jpg",
    lat: 30.8,
    lng: 104.2,
    paleoLat: -6,
    paleoLng: 72,
    impact: 98,
    spread: 75,
    policy: 0,
    extinct: false,
    emoji: "🦐"
  },
  {
    id: "bio-first-insects",
    year: -410000000,
    domain: "bio",
    category: "昆虫",
    titleZh: "最早昆虫登场",
    titleEn: "First Insects Appear",
    descZh: "昆虫成为陆地生态关键角色，后续推动授粉和分解循环。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Meganeura_fossile.jpg/320px-Meganeura_fossile.jpg",
    lat: 56.1,
    lng: -3.3,
    paleoLat: -18,
    paleoLng: 22,
    impact: 84,
    spread: 66,
    policy: 0,
    extinct: false,
    emoji: "🪲"
  },
  {
    id: "bio-giant-dragonfly",
    year: -300000000,
    domain: "bio",
    category: "昆虫",
    titleZh: "巨脉蜻蜓时代",
    titleEn: "Age of Giant Dragonflies",
    descZh: "含氧较高的环境支持了巨型昆虫。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Meganeura_monnyi_adult.jpg/320px-Meganeura_monnyi_adult.jpg",
    lat: 51.2,
    lng: 6.8,
    paleoLat: -28,
    paleoLng: 40,
    impact: 74,
    spread: 55,
    policy: 0,
    extinct: true,
    emoji: "🪰"
  },
  {
    id: "bio-pangaea",
    year: -335000000,
    domain: "bio",
    category: "大陆漂移",
    titleZh: "盘古大陆形成",
    titleEn: "Pangaea Forms",
    descZh: "大陆拼合成超大陆，生物迁徙路径发生重构。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Pangea_to_present.gif/320px-Pangea_to_present.gif",
    lat: 0,
    lng: 20,
    paleoLat: 0,
    paleoLng: 20,
    impact: 92,
    spread: 40,
    policy: 0,
    extinct: false,
    emoji: "🌍"
  },
  {
    id: "bio-permian-extinction",
    year: -252000000,
    domain: "extinction",
    category: "灭绝事件",
    titleZh: "二叠纪大灭绝",
    titleEn: "Permian Mass Extinction",
    descZh: "已知最大生物灭绝事件，海洋与陆地物种大幅消失。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Permian-Triassic_Event_graph.svg/320px-Permian-Triassic_Event_graph.svg.png",
    lat: 62.5,
    lng: 91.5,
    paleoLat: 50,
    paleoLng: 75,
    impact: 100,
    spread: 90,
    policy: 0,
    extinct: true,
    emoji: "☠️"
  },
  {
    id: "bio-first-dinosaur",
    year: -230000000,
    domain: "bio",
    category: "恐龙",
    titleZh: "最早恐龙出现",
    titleEn: "First Dinosaurs",
    descZh: "早期恐龙在冈瓦纳大陆扩散，开启恐龙时代。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Eoraptor_lunensis.jpg/320px-Eoraptor_lunensis.jpg",
    lat: -30.6,
    lng: -68.2,
    paleoLat: -48,
    paleoLng: 35,
    impact: 88,
    spread: 62,
    policy: 0,
    extinct: true,
    emoji: "🦖"
  },
  {
    id: "bio-jurassic",
    year: -201000000,
    domain: "bio",
    category: "恐龙",
    titleZh: "侏罗纪生态扩张",
    titleEn: "Jurassic Expansion",
    descZh: "大型蜥脚类和肉食恐龙分化，海洋爬行动物繁荣。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Brachiosaurus_DB.jpg/320px-Brachiosaurus_DB.jpg",
    lat: 44.0,
    lng: -110.0,
    paleoLat: 18,
    paleoLng: -10,
    impact: 86,
    spread: 70,
    policy: 0,
    extinct: true,
    emoji: "🦕"
  },
  {
    id: "bio-archaeopteryx",
    year: -150000000,
    domain: "bio",
    category: "鸟类起源",
    titleZh: "始祖鸟化石",
    titleEn: "Archaeopteryx Fossils",
    descZh: "恐龙向鸟类演化的重要证据。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Archaeopteryx_lithographica_%28Berlin_specimen%29.jpg/320px-Archaeopteryx_lithographica_%28Berlin_specimen%29.jpg",
    lat: 49.0,
    lng: 11.1,
    paleoLat: 30,
    paleoLng: 5,
    impact: 78,
    spread: 48,
    policy: 0,
    extinct: true,
    emoji: "🪶"
  },
  {
    id: "bio-flowering",
    year: -125000000,
    domain: "bio",
    category: "植物演化",
    titleZh: "被子植物兴起",
    titleEn: "Flowering Plants Rise",
    descZh: "花和果实体系兴起，昆虫-植物协同加速。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Archaefructus_liaoningensis.jpg/320px-Archaefructus_liaoningensis.jpg",
    lat: 41.0,
    lng: 121.0,
    paleoLat: 34,
    paleoLng: 115,
    impact: 82,
    spread: 73,
    policy: 0,
    extinct: false,
    emoji: "🌸"
  },
  {
    id: "bio-mosasaur",
    year: -94000000,
    domain: "bio",
    category: "海洋生物",
    titleZh: "沧龙主宰近海",
    titleEn: "Mosasaur Era",
    descZh: "白垩纪晚期海洋顶级掠食者之一。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Mosasaurus_hoffmanni.jpg/320px-Mosasaurus_hoffmanni.jpg",
    lat: 50.9,
    lng: 5.7,
    paleoLat: 36,
    paleoLng: 0,
    impact: 76,
    spread: 58,
    policy: 0,
    extinct: true,
    emoji: "🦈"
  },
  {
    id: "bio-tyrannosaurus",
    year: -68000000,
    domain: "bio",
    category: "恐龙",
    titleZh: "霸王龙时代",
    titleEn: "T. rex Era",
    descZh: "晚白垩纪北美顶级肉食恐龙。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Tyrannosaurus_Rex_Holotype.jpg/320px-Tyrannosaurus_Rex_Holotype.jpg",
    lat: 47.0,
    lng: -107.0,
    paleoLat: 42,
    paleoLng: -95,
    impact: 92,
    spread: 52,
    policy: 0,
    extinct: true,
    emoji: "🦖"
  },
  {
    id: "bio-chicxulub",
    year: -66000000,
    domain: "extinction",
    category: "灭绝事件",
    titleZh: "尤卡坦陨石撞击",
    titleEn: "Chicxulub Impact",
    descZh: "撞击引发全球生态灾变，非鸟类恐龙大规模灭绝。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Chicxulub_impact_-_artist_impression.jpg/320px-Chicxulub_impact_-_artist_impression.jpg",
    lat: 21.3,
    lng: -89.5,
    paleoLat: 21.3,
    paleoLng: -89.5,
    impact: 100,
    spread: 95,
    policy: 0,
    extinct: true,
    emoji: "☄️",
    effect: "meteor"
  },
  {
    id: "bio-birds-survive",
    year: -65000000,
    domain: "bio",
    category: "鸟类",
    titleZh: "鸟类谱系存续",
    titleEn: "Bird Lineage Survives",
    descZh: "部分小型羽毛类谱系延续到现代鸟类。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Birds_collage.jpg/320px-Birds_collage.jpg",
    lat: 30.0,
    lng: 103.0,
    paleoLat: 18,
    paleoLng: 95,
    impact: 75,
    spread: 64,
    policy: 0,
    extinct: false,
    emoji: "🕊️"
  },
  {
    id: "bio-mammal-radiation",
    year: -56000000,
    domain: "bio",
    category: "哺乳类",
    titleZh: "哺乳动物辐射扩张",
    titleEn: "Mammal Radiation",
    descZh: "恐龙灭绝后，哺乳动物快速占据多生态位。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mammal_collage.png/320px-Mammal_collage.png",
    lat: 44.0,
    lng: -100.0,
    paleoLat: 32,
    paleoLng: -70,
    impact: 90,
    spread: 75,
    policy: 0,
    extinct: false,
    emoji: "🐘"
  },
  {
    id: "bio-early-whale",
    year: -50000000,
    domain: "bio",
    category: "海洋生物",
    titleZh: "鲸类回归海洋",
    titleEn: "Early Whales Return to Sea",
    descZh: "古鲸类在特提斯海沿岸演化，逐渐完全适应海洋。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Pakicetus_DB.jpg/320px-Pakicetus_DB.jpg",
    lat: 32.5,
    lng: 73.0,
    paleoLat: 12,
    paleoLng: 62,
    impact: 83,
    spread: 60,
    policy: 0,
    extinct: false,
    emoji: "🐋"
  },
  {
    id: "bio-grassland",
    year: -34000000,
    domain: "bio",
    category: "生态系统",
    titleZh: "草原生态扩展",
    titleEn: "Grassland Expansion",
    descZh: "草原扩展推动奔跑型食草与捕食动物共演化。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Grassland_Ecosystem.jpg/320px-Grassland_Ecosystem.jpg",
    lat: 39.0,
    lng: 105.0,
    paleoLat: 22,
    paleoLng: 96,
    impact: 71,
    spread: 80,
    policy: 0,
    extinct: false,
    emoji: "🌾"
  },
  {
    id: "bio-megalodon",
    year: -16000000,
    domain: "bio",
    category: "海洋生物",
    titleZh: "巨齿鲨高峰",
    titleEn: "Megalodon Peak",
    descZh: "中新世海洋顶级掠食者之一。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Carcharocles_megalodon.jpg/320px-Carcharocles_megalodon.jpg",
    lat: 35.0,
    lng: -6.0,
    paleoLat: 28,
    paleoLng: -12,
    impact: 79,
    spread: 62,
    policy: 0,
    extinct: true,
    emoji: "🦈"
  },
  {
    id: "bio-homo",
    year: -300000,
    domain: "bio",
    category: "人类",
    titleZh: "智人出现",
    titleEn: "Homo sapiens Emerges",
    descZh: "智人在非洲形成并逐步全球扩散。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Homo_sapiens_skull.jpg/320px-Homo_sapiens_skull.jpg",
    lat: 9.0,
    lng: 39.7,
    paleoLat: 9.0,
    paleoLng: 39.7,
    impact: 96,
    spread: 88,
    policy: 0,
    extinct: false,
    emoji: "🧑"
  },
  {
    id: "bio-mammoth-end",
    year: -12000,
    domain: "extinction",
    category: "灭绝事件",
    titleZh: "猛犸象晚期灭绝",
    titleEn: "Late Mammoth Extinction",
    descZh: "气候与人类活动共同作用下，猛犸象逐步消失。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Woolly_mammoth_-_Mammuthus_primigenius.jpg/320px-Woolly_mammoth_-_Mammuthus_primigenius.jpg",
    lat: 71.2,
    lng: 179.5,
    paleoLat: 71.2,
    paleoLng: 179.5,
    impact: 66,
    spread: 42,
    policy: 0,
    extinct: true,
    emoji: "🦣"
  },
  {
    id: "bio-honeybee",
    year: -100000000,
    domain: "bio",
    category: "昆虫",
    titleZh: "蜜蜂与开花植物协同",
    titleEn: "Bee-Flower Coevolution",
    descZh: "授粉系统提高植物繁殖效率，影响现代农业与生态稳定。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Apis_mellifera_Western_honey_bee.jpg/320px-Apis_mellifera_Western_honey_bee.jpg",
    lat: 48.8,
    lng: 2.3,
    paleoLat: 30,
    paleoLng: -2,
    impact: 86,
    spread: 85,
    policy: 0,
    extinct: false,
    emoji: "🐝"
  },
  {
    id: "bio-ocean-modern",
    year: 2020,
    domain: "bio",
    category: "海洋生物",
    titleZh: "现代海洋多样性保护",
    titleEn: "Modern Marine Biodiversity Protection",
    descZh: "海洋保护区和渔业管理影响鲸类、鲨类与珊瑚生态。",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Coral_reef_and_fish.jpg/320px-Coral_reef_and_fish.jpg",
    lat: -17.0,
    lng: 146.0,
    paleoLat: -17.0,
    paleoLng: 146.0,
    impact: 72,
    spread: 78,
    policy: 48,
    extinct: false,
    emoji: "🐠"
  }
];
